title: FoamValue
description: >- 
  在这里为你的新网站写一个很棒的描述。
baseurl: "/"
url: "http://www.chenxinjie.cn"

permalink: /article/:categories/:year/:month/:day/:title:output_ext
paginate: 5
paginate_path: "/page:num/"

# nav name
nav:
  -
    name: 首页
    url: /
  - 
    name: 标签
    url: /tag
  -
    name: 归档
    url: /archive
  -
    name: 关于我
    url: /about

plugins:
  - jekyll-feed
  - jekyll-paginate
