name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1.2.1
      - name: Jekyll Action
        uses:  lemonarc/jekyll-action@1.0.0
      - name: Install and Build
        run: |
          jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: _site
