name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
          
      - name: Jekyll Build
        # You may pin to the exact commit or the version.
        # uses: kshehadeh/jekyll-s3-action@220371747871b9aa1b635fb30a57693891e37982
        uses: kshehadeh/jekyll-s3-action@0.1
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: _site
