name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
          
      - name: Jekyll Action
        # You may pin to the exact commit or the version.
        # uses: lemonarc/jekyll-action@2d5e5a2316cd9d4b74ad33da527d6d9be5bff8d1
        uses: lemonarc/jekyll-action@1.0.0
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: _site
