name: Build Jekyll

on: 
  schedule:
    - cron:  '30 23 * * *'
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Jekyll Deploy Action
        uses: jeffreytse/jekyll-deploy-action@v0.5.0
        with:
          token: ${{ secrets.JEKYLL_PAT }}
